// Generated by scripts/development/generate-cambridge-swift-contract.py. Do not edit.
import Foundation

public enum CamBridgeContract {
    public static let name = "cambridge-stream"
    public static let protocolVersion = 6

    public enum Control {
        public static let framing = "uint32-be-length-prefixed-json"
        public static let maximumMessageBytes = 8192
        public static let connectTimeoutMilliseconds = 2000
        public static let requestTimeoutMilliseconds = 2000
    }

    public enum Discovery {
        public static let version = 1
        public static let serviceType = "_cambridge._tcp"
        public static let txtKeys = ["id", "name", "protocolVersion", "codec", "discoveryVersion", "address<N>"]
        public static let addressKeyPrefix = "address"
        public static let addressFamily = "ipv4"
        public static let maximumAddressCount = 16
    }

    public enum Receiver {
        public static let defaultId = "cambridge-obs-source"
        public static let defaultDisplayName = "OBS receiver"
    }

    public enum Defaults {
        public static let controlPort = 55031
        public static let mediaPortOffset = 1
    }

    public enum Geometry {
        public static let minimumDimension = 16
        public static let dimensionAlignment = 2
        public static let maximumLongEdge = 3840
        public static let maximumShortEdge = 2160
        public static let rotationDegrees = [0, 90, 180, 270]
    }

    public enum Video {
        public static let minimumFps = 1
        public static let maximumFps = 120
    }

    public enum Bitrate {
        public static let minimumBps = 100000
        public static let maximumBps = 100000000
    }

    public enum Media {
        public static let transport = "rtp-h264-udp-unicast"
        public static let payloadType = 96
        public static let clockRateHz = 90000
        public static let rtpHeaderBytes = 12
        public static let mtuBytes = 1200
        public static let maxDatagramBytes = 1500
        public static let maxAccessUnitBytes = 8388608
        public static let maxInFlightAccessUnits = 2
        public static let maxReorderPackets = 64
        public static let mailboxCapacity = 1
        public static let texturePoolSlots = 3
        public static let maximumDecoderQueueAgeMilliseconds = 100
        public static let maximumLiveFrameAgeMilliseconds = 250
        public static let reorderDeadlineMs = 20
        public static let keyframeIntervalSeconds = 1
    }

    public enum Codec {
        public static let h264 = "h264"
    }

    public enum Validation {
        public static let maximumIdentifierLength = 128
        public static let maximumProfileIdentifierLength = 64
        public static let maximumErrorLength = 512
        public static let minimumPort = 1
        public static let maximumPort = 65535
        public static let minimumGeneration = 1
    }

    public enum MessageType {
        public static let probe = "probe"
        public static let capabilities = "capabilities"
        public static let hello = "hello"
        public static let accepted = "accepted"
        public static let stop = "stop"
        public static let error = "error"
    }

    public enum MessageShape {
        public static let probe = "{protocolVersion:6, type:probe, requestId}"
        public static let capabilities = "{protocolVersion:6, type:capabilities, requestId, receiverId, displayName, maxLongEdge, maxShortEdge}"
        public static let hello = "{protocolVersion:6, type:hello, sessionId, generation, profileId, codec, codedWidth, codedHeight, rotationDegrees, fps, bitrateBps}"
        public static let accepted = "{protocolVersion:6, type:accepted, sessionId, generation, profileId, mediaPort, maxLongEdge, maxShortEdge}"
        public static let stop = "{protocolVersion:6, type:stop, sessionId, generation}"
        public static let error = "{protocolVersion:6, type:error, error}"
    }
}
