// Generated by scripts/development/generate-cambridge-sender-modes.py. Do not edit.
import Foundation

public enum SenderVideoCatalog {
    public static let profileID = "sender"
    public static let bitrateUnitBps = 1_000_000
    public static let minimumBitrateMbps = 1
    public static let maximumBitrateMbps = 100
    public static let keyframeIntervalSeconds = 1

    public static let fullHd = VideoResolution(
        id: "full-hd",
        displayName: "Full HD",
        codedWidth: 1920,
        codedHeight: 1080
    )

    public static let resolution2k = VideoResolution(
        id: "2k",
        displayName: "2K",
        codedWidth: 2560,
        codedHeight: 1440
    )

    public static let resolutions: [VideoResolution] = [fullHd, resolution2k]
    public static let frameRates: [Int] = [30, 60]
    public static let defaultResolution = fullHd
    public static let defaultFrameRate = 30

    public static func resolution(id: String) -> VideoResolution? {
        resolutions.first { $0.id == id }
    }

    public static func suggestedBitrateBps(resolution: VideoResolution, fps: Int) -> Int? {
        switch (resolution.id, fps) {
        case ("full-hd", 30): 5_000_000
        case ("full-hd", 60): 10_000_000
        case ("2k", 30): 9_000_000
        case ("2k", 60): 18_000_000
        default: nil
        }
    }
}
