// Generated by scripts/development/generate-cambridge-sender-modes.py. Do not edit.
import Foundation

public extension VideoMode {
    /// Generated from sender/cambridge-video-modes.json.
    static let mode720p30 = VideoMode(
        id: "720p30",
        codedWidth: 1280,
        codedHeight: 720,
        fps: 30,
        minimumBitrateBps: 2000000,
        defaultBitrateBps: 4000000,
        maximumBitrateBps: 8000000,
        bitrateStepBps: 1000000,
        keyframeIntervalSeconds: 1,
        availability: .testOnly
    )
    /// Generated from sender/cambridge-video-modes.json.
    static let mode1080p30 = VideoMode(
        id: "1080p30",
        codedWidth: 1920,
        codedHeight: 1080,
        fps: 30,
        minimumBitrateBps: 4000000,
        defaultBitrateBps: 8000000,
        maximumBitrateBps: 16000000,
        bitrateStepBps: 1000000,
        keyframeIntervalSeconds: 1,
        availability: .product
    )
    /// Generated from sender/cambridge-video-modes.json.
    static let mode1080p60 = VideoMode(
        id: "1080p60",
        codedWidth: 1920,
        codedHeight: 1080,
        fps: 60,
        minimumBitrateBps: 8000000,
        defaultBitrateBps: 16000000,
        maximumBitrateBps: 32000000,
        bitrateStepBps: 1000000,
        keyframeIntervalSeconds: 1,
        availability: .product
    )
    /// Generated from sender/cambridge-video-modes.json.
    static let mode2k30 = VideoMode(
        id: "2k30",
        codedWidth: 2560,
        codedHeight: 1440,
        fps: 30,
        minimumBitrateBps: 9000000,
        defaultBitrateBps: 18000000,
        maximumBitrateBps: 36000000,
        bitrateStepBps: 1000000,
        keyframeIntervalSeconds: 1,
        availability: .product
    )
    /// Generated from sender/cambridge-video-modes.json.
    static let mode2k60 = VideoMode(
        id: "2k60",
        codedWidth: 2560,
        codedHeight: 1440,
        fps: 60,
        minimumBitrateBps: 18000000,
        defaultBitrateBps: 36000000,
        maximumBitrateBps: 72000000,
        bitrateStepBps: 1000000,
        keyframeIntervalSeconds: 1,
        availability: .product
    )

    static let productModes: [VideoMode] = [mode1080p30, mode1080p60, mode2k30, mode2k60]
    static let allModes: [VideoMode] = [mode720p30, mode1080p30, mode1080p60, mode2k30, mode2k60]
    static let defaultMode: VideoMode = mode2k30
}
