#!/usr/bin/env python3
"""Generate Android and Swift typed sender modes from the shared catalog."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = REPOSITORY_ROOT / "sender/cambridge-video-modes.json"
ANDROID_OUTPUT_PATH = REPOSITORY_ROOT / "sender/android/app/src/main/java/dev/cambridge/sender/session/VideoProfiles.kt"
SWIFT_OUTPUT_PATH = (
    REPOSITORY_ROOT
    / "sender/ios/Packages/CamBridgeCore/Sources/CamBridgeCore/Contract/VideoModes.generated.swift"
)
GENERATED_ANDROID_HEADER = "// Generated by scripts/development/generate-cambridge-sender-modes.py. Do not edit.\n"
GENERATED_SWIFT_HEADER = "// Generated by scripts/development/generate-cambridge-sender-modes.py. Do not edit.\n"
MODE_KEYS = {
    "id", "codedWidth", "codedHeight", "fps", "minimumBitrateBps", "defaultBitrateBps",
    "maximumBitrateBps", "bitrateStepBps", "keyframeIntervalSeconds", "availability",
}
CATALOG_KEYS = {"catalogVersion", "defaultModeId", "modes"}
IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9-]*$")


def load_catalog() -> dict[str, Any]:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    if not isinstance(catalog, dict) or set(catalog) != CATALOG_KEYS:
        raise ValueError("the sender mode catalog has an unsupported top-level shape")
    if catalog["catalogVersion"] != 1 or not isinstance(catalog["modes"], list):
        raise ValueError("the sender mode catalog must be version 1 with a mode list")
    if not catalog["modes"]:
        raise ValueError("the sender mode catalog cannot be empty")
    ids: set[str] = set()
    for mode in catalog["modes"]:
        if not isinstance(mode, dict) or set(mode) != MODE_KEYS:
            raise ValueError("a sender mode has an unsupported shape")
        mode_id = mode["id"]
        if not isinstance(mode_id, str) or not IDENTIFIER_PATTERN.fullmatch(mode_id) or mode_id in ids:
            raise ValueError(f"invalid or duplicate sender mode ID: {mode_id!r}")
        ids.add(mode_id)
        if mode["availability"] not in {"product", "test-only"}:
            raise ValueError(f"unsupported availability for mode {mode_id}")
        numeric_fields = MODE_KEYS - {"id", "availability"}
        if not all(isinstance(mode[field], int) and mode[field] > 0 for field in numeric_fields):
            raise ValueError(f"mode {mode_id} has a non-positive or non-integer value")
        if not (mode["minimumBitrateBps"] <= mode["defaultBitrateBps"] <= mode["maximumBitrateBps"]):
            raise ValueError(f"mode {mode_id} has an invalid bitrate range")
    if catalog["defaultModeId"] not in ids:
        raise ValueError("the sender catalog default mode is not present")
    return catalog


def kotlin_identifier(mode_id: str) -> str:
    return "PROFILE_" + mode_id.upper()


def swift_identifier(mode_id: str) -> str:
    return "mode" + mode_id[0].upper() + mode_id[1:]


def render_android(catalog: dict[str, Any]) -> str:
    modes = catalog["modes"]
    product_modes = [mode for mode in modes if mode["availability"] == "product"]
    lines = [GENERATED_ANDROID_HEADER.rstrip("\n"), "package dev.cambridge.sender.session", "", "import dev.cambridge.sender.model.VideoProfile", "", "object VideoProfiles {"]
    lines.append("    const val MEGABIT = 1_000_000")
    for mode in modes:
        name = kotlin_identifier(mode["id"])
        lines.extend([
            "",
            f"    val {name}: VideoProfile = VideoProfile(",
            f"        id = \"{mode['id']}\",",
            f"        width = {mode['codedWidth']},",
            f"        height = {mode['codedHeight']},",
            f"        fps = {mode['fps']},",
            f"        minimumBitrateBps = {mode['minimumBitrateBps']},",
            f"        defaultBitrateBps = {mode['defaultBitrateBps']},",
            f"        maximumBitrateBps = {mode['maximumBitrateBps']},",
            f"        bitrateStepBps = {mode['bitrateStepBps']},",
            f"        keyframeIntervalSeconds = {mode['keyframeIntervalSeconds']},",
            "    )",
        ])
    product_names = ", ".join(kotlin_identifier(mode["id"]) for mode in product_modes)
    all_names = ", ".join(kotlin_identifier(mode["id"]) for mode in modes)
    default_name = kotlin_identifier(catalog["defaultModeId"])
    lines.extend([
        "",
        f"    val normal: List<VideoProfile> = listOf({product_names})",
        f"    val all: List<VideoProfile> = listOf({all_names})",
        "    val qualityProfiles: List<VideoProfile> = normal.distinctBy { profile -> profile.width to profile.height }",
        f"    val default: VideoProfile = {default_name}",
        "",
        "    fun modeFor(width: Int, height: Int, fps: Int): VideoProfile? = all.firstOrNull { profile ->",
        "        profile.width == width && profile.height == height && profile.fps == fps",
        "    }",
        "",
        "    fun modeId(width: Int, height: Int, fps: Int): String? = modeFor(width, height, fps)?.id",
        "",
        "    fun profilesForResolution(profile: VideoProfile): List<VideoProfile> = all.filter { candidate ->",
        "        candidate.width == profile.width && candidate.height == profile.height",
        "    }",
        "",
        "    fun profileForResolution(width: Int, height: Int, fps: Int): VideoProfile? = modeFor(width, height, fps)",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_swift(catalog: dict[str, Any]) -> str:
    modes = catalog["modes"]
    lines = [GENERATED_SWIFT_HEADER.rstrip("\n"), "import Foundation", "", "public extension VideoMode {"]
    for mode in modes:
        identifier = swift_identifier(mode["id"])
        availability = ".product" if mode["availability"] == "product" else ".testOnly"
        lines.extend([
            "    /// Generated from sender/cambridge-video-modes.json.",
            f"    static let {identifier} = VideoMode(",
            f"        id: \"{mode['id']}\",",
            f"        codedWidth: {mode['codedWidth']},",
            f"        codedHeight: {mode['codedHeight']},",
            f"        fps: {mode['fps']},",
            f"        minimumBitrateBps: {mode['minimumBitrateBps']},",
            f"        defaultBitrateBps: {mode['defaultBitrateBps']},",
            f"        maximumBitrateBps: {mode['maximumBitrateBps']},",
            f"        bitrateStepBps: {mode['bitrateStepBps']},",
            f"        keyframeIntervalSeconds: {mode['keyframeIntervalSeconds']},",
            f"        availability: {availability}",
            "    )",
        ])
    product_ids = [swift_identifier(mode["id"]) for mode in modes if mode["availability"] == "product"]
    all_ids = [swift_identifier(mode["id"]) for mode in modes]
    lines.extend([
        "",
        f"    static let productModes: [VideoMode] = [{', '.join(product_ids)}]",
        f"    static let allModes: [VideoMode] = [{', '.join(all_ids)}]",
        f"    static let defaultMode: VideoMode = {swift_identifier(catalog['defaultModeId'])}",
        "}",
        "",
    ])
    return "\n".join(lines)


def write_or_check(path: Path, expected: str, check: bool, label: str) -> bool:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            print(f"stale generated {label}: {path}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"generated {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated declarations are stale")
    arguments = parser.parse_args()
    catalog = load_catalog()
    android = render_android(catalog)
    swift = render_swift(catalog)
    valid = write_or_check(ANDROID_OUTPUT_PATH, android, arguments.check, "Android sender modes")
    valid = write_or_check(SWIFT_OUTPUT_PATH, swift, arguments.check, "Swift sender modes") and valid
    if arguments.check and valid:
        print("CamBridge sender mode generation: current")
    return 0 if valid else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"CamBridge sender mode generation: {error}", file=sys.stderr)
        raise SystemExit(1)
