#!/usr/bin/env python3
"""Generate Android compatibility profiles and native Swift sender settings."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = REPOSITORY_ROOT / "sender/cambridge-video-settings.json"
PROTOCOL_PATH = REPOSITORY_ROOT / "protocol/cambridge-stream-contract.json"
ANDROID_OUTPUT_PATH = REPOSITORY_ROOT / "sender/android/app/src/main/java/dev/cambridge/sender/session/VideoProfiles.kt"
SWIFT_OUTPUT_PATH = (
    REPOSITORY_ROOT
    / "sender/ios/Packages/CamBridgeCore/Sources/CamBridgeCore/Contract/SenderVideoSettings.generated.swift"
)
GENERATED_ANDROID_HEADER = "// Generated by scripts/development/generate-cambridge-sender-modes.py. Do not edit.\n"
GENERATED_SWIFT_HEADER = "// Generated by scripts/development/generate-cambridge-sender-modes.py. Do not edit.\n"
CATALOG_VERSION = 2
CATALOG_KEYS = {
    "catalogVersion",
    "profileId",
    "bitrateUnitBps",
    "minimumBitrateMbps",
    "maximumBitrateMbps",
    "keyframeIntervalSeconds",
    "defaultResolutionId",
    "defaultFps",
    "resolutions",
    "frameRates",
    "suggestedBitratesBps",
}
RESOLUTION_KEYS = {"id", "displayName", "compatibilityIdPrefix", "codedWidth", "codedHeight"}
SUGGESTION_KEYS = {"resolutionId", "fps", "bitrateBps"}
IDENTIFIER_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def load_catalog() -> dict[str, Any]:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    protocol = json.loads(PROTOCOL_PATH.read_text(encoding="utf-8"))
    if not isinstance(catalog, dict) or set(catalog) != CATALOG_KEYS:
        raise ValueError("the sender settings catalog has an unsupported top-level shape")
    if catalog["catalogVersion"] != CATALOG_VERSION:
        raise ValueError(f"the sender settings catalog must be version {CATALOG_VERSION}")
    positive_fields = (
        "bitrateUnitBps",
        "minimumBitrateMbps",
        "maximumBitrateMbps",
        "keyframeIntervalSeconds",
        "defaultFps",
    )
    if not all(isinstance(catalog[field], int) and catalog[field] > 0 for field in positive_fields):
        raise ValueError("the sender settings catalog contains a non-positive numeric setting")
    if catalog["minimumBitrateMbps"] > catalog["maximumBitrateMbps"]:
        raise ValueError("the sender bitrate input range is reversed")
    minimum_bitrate_bps = catalog["minimumBitrateMbps"] * catalog["bitrateUnitBps"]
    maximum_bitrate_bps = catalog["maximumBitrateMbps"] * catalog["bitrateUnitBps"]
    if minimum_bitrate_bps < protocol["bitrate"]["minimumBps"] or maximum_bitrate_bps > protocol["bitrate"]["maximumBps"]:
        raise ValueError("the sender bitrate input range exceeds the v6 contract")

    resolutions = catalog["resolutions"]
    if not isinstance(resolutions, list) or not resolutions:
        raise ValueError("the sender settings catalog requires resolutions")
    resolution_ids: set[str] = set()
    compatibility_prefixes: set[str] = set()
    for resolution in resolutions:
        if not isinstance(resolution, dict) or set(resolution) != RESOLUTION_KEYS:
            raise ValueError("a sender resolution has an unsupported shape")
        resolution_id = resolution["id"]
        prefix = resolution["compatibilityIdPrefix"]
        if not isinstance(resolution_id, str) or not IDENTIFIER_PATTERN.fullmatch(resolution_id) or resolution_id in resolution_ids:
            raise ValueError(f"invalid or duplicate resolution ID: {resolution_id!r}")
        if not isinstance(prefix, str) or not IDENTIFIER_PATTERN.fullmatch(prefix) or prefix in compatibility_prefixes:
            raise ValueError(f"invalid or duplicate compatibility prefix: {prefix!r}")
        if not isinstance(resolution["displayName"], str) or not resolution["displayName"].strip():
            raise ValueError(f"resolution {resolution_id} requires a display name")
        if not all(isinstance(resolution[field], int) and resolution[field] > 0 for field in ("codedWidth", "codedHeight")):
            raise ValueError(f"resolution {resolution_id} has invalid dimensions")
        resolution_ids.add(resolution_id)
        compatibility_prefixes.add(prefix)
    if catalog["defaultResolutionId"] not in resolution_ids:
        raise ValueError("the default resolution is not present")

    frame_rates = catalog["frameRates"]
    if not isinstance(frame_rates, list) or not frame_rates or len(frame_rates) != len(set(frame_rates)):
        raise ValueError("the sender settings catalog requires unique frame rates")
    if not all(
        isinstance(fps, int)
        and protocol["video"]["minimumFps"] <= fps <= protocol["video"]["maximumFps"]
        for fps in frame_rates
    ):
        raise ValueError("a sender frame rate exceeds the v6 contract")
    if catalog["defaultFps"] not in frame_rates:
        raise ValueError("the default frame rate is not present")

    suggestions = catalog["suggestedBitratesBps"]
    expected_combinations = {(resolution_id, fps) for resolution_id in resolution_ids for fps in frame_rates}
    actual_combinations: set[tuple[str, int]] = set()
    for suggestion in suggestions:
        if not isinstance(suggestion, dict) or set(suggestion) != SUGGESTION_KEYS:
            raise ValueError("a suggested bitrate has an unsupported shape")
        combination = (suggestion["resolutionId"], suggestion["fps"])
        if combination not in expected_combinations or combination in actual_combinations:
            raise ValueError(f"invalid or duplicate bitrate suggestion: {combination!r}")
        bitrate_bps = suggestion["bitrateBps"]
        if not isinstance(bitrate_bps, int) or not minimum_bitrate_bps <= bitrate_bps <= maximum_bitrate_bps:
            raise ValueError(f"suggested bitrate for {combination!r} is outside the product range")
        actual_combinations.add(combination)
    if actual_combinations != expected_combinations:
        raise ValueError("every resolution and frame-rate combination requires one suggested bitrate")
    return catalog


def compatibility_modes(catalog: dict[str, Any]) -> list[dict[str, Any]]:
    suggestions = {
        (suggestion["resolutionId"], suggestion["fps"]): suggestion["bitrateBps"]
        for suggestion in catalog["suggestedBitratesBps"]
    }
    modes = []
    for resolution in catalog["resolutions"]:
        for fps in catalog["frameRates"]:
            modes.append({
                "id": f"{resolution['compatibilityIdPrefix']}{fps}",
                "codedWidth": resolution["codedWidth"],
                "codedHeight": resolution["codedHeight"],
                "fps": fps,
                "defaultBitrateBps": suggestions[(resolution["id"], fps)],
            })
    return modes


def kotlin_identifier(mode_id: str) -> str:
    return "PROFILE_" + mode_id.upper().replace("-", "_")


def swift_identifier(resolution_id: str) -> str:
    parts = resolution_id.split("-")
    identifier = parts[0] + "".join(part.title() for part in parts[1:])
    return f"resolution{identifier}" if identifier[0].isdigit() else identifier


def format_integer(value: int) -> str:
    return f"{value:_}"


def render_android(catalog: dict[str, Any]) -> str:
    modes = compatibility_modes(catalog)
    minimum_bitrate_bps = catalog["minimumBitrateMbps"] * catalog["bitrateUnitBps"]
    maximum_bitrate_bps = catalog["maximumBitrateMbps"] * catalog["bitrateUnitBps"]
    lines = [
        GENERATED_ANDROID_HEADER.rstrip("\n"),
        "package dev.cambridge.sender.session",
        "",
        "import dev.cambridge.sender.model.VideoProfile",
        "",
        "object VideoProfiles {",
        f"    const val MEGABIT = {format_integer(catalog['bitrateUnitBps'])}",
        f"    const val PROFILE_ID = \"{catalog['profileId']}\"",
    ]
    for mode in modes:
        name = kotlin_identifier(mode["id"])
        lines.extend([
            "",
            f"    val {name}: VideoProfile = VideoProfile(",
            f"        id = \"{mode['id']}\",",
            f"        width = {mode['codedWidth']},",
            f"        height = {mode['codedHeight']},",
            f"        fps = {mode['fps']},",
            f"        minimumBitrateBps = {format_integer(minimum_bitrate_bps)},",
            f"        defaultBitrateBps = {format_integer(mode['defaultBitrateBps'])},",
            f"        maximumBitrateBps = {format_integer(maximum_bitrate_bps)},",
            f"        bitrateStepBps = {format_integer(catalog['bitrateUnitBps'])},",
            f"        keyframeIntervalSeconds = {catalog['keyframeIntervalSeconds']},",
            "    )",
        ])
    mode_names = ", ".join(kotlin_identifier(mode["id"]) for mode in modes)
    default_resolution = next(
        resolution for resolution in catalog["resolutions"]
        if resolution["id"] == catalog["defaultResolutionId"]
    )
    default_mode_id = f"{default_resolution['compatibilityIdPrefix']}{catalog['defaultFps']}"
    lines.extend([
        "",
        f"    val normal: List<VideoProfile> = listOf({mode_names})",
        "    val all: List<VideoProfile> = normal",
        "    val qualityProfiles: List<VideoProfile> = normal.distinctBy { profile -> profile.width to profile.height }",
        f"    val default: VideoProfile = {kotlin_identifier(default_mode_id)}",
        "",
        "    fun modeFor(width: Int, height: Int, fps: Int): VideoProfile? = all.firstOrNull { profile ->",
        "        profile.width == width && profile.height == height && profile.fps == fps",
        "    }",
        "",
        "    fun modeId(width: Int, height: Int, fps: Int): String? = modeFor(width, height, fps)?.id",
        "",
        "    fun profilesForResolution(profile: VideoProfile): List<VideoProfile> = all.filter { candidate ->",
        "        candidate.width == profile.width && candidate.height == profile.height",
        "    }",
        "",
        "    fun profileForResolution(width: Int, height: Int, fps: Int): VideoProfile? = modeFor(width, height, fps)",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_swift(catalog: dict[str, Any]) -> str:
    resolution_names = {
        resolution["id"]: swift_identifier(resolution["id"])
        for resolution in catalog["resolutions"]
    }
    default_name = resolution_names[catalog["defaultResolutionId"]]
    lines = [
        GENERATED_SWIFT_HEADER.rstrip("\n"),
        "import Foundation",
        "",
        "public enum SenderVideoCatalog {",
        f"    public static let profileID = \"{catalog['profileId']}\"",
        f"    public static let bitrateUnitBps = {format_integer(catalog['bitrateUnitBps'])}",
        f"    public static let minimumBitrateMbps = {catalog['minimumBitrateMbps']}",
        f"    public static let maximumBitrateMbps = {catalog['maximumBitrateMbps']}",
        f"    public static let keyframeIntervalSeconds = {catalog['keyframeIntervalSeconds']}",
        "",
    ]
    for resolution in catalog["resolutions"]:
        name = resolution_names[resolution["id"]]
        lines.extend([
            f"    public static let {name} = VideoResolution(",
            f"        id: \"{resolution['id']}\",",
            f"        displayName: \"{resolution['displayName']}\",",
            f"        codedWidth: {resolution['codedWidth']},",
            f"        codedHeight: {resolution['codedHeight']}",
            "    )",
            "",
        ])
    all_names = ", ".join(resolution_names[resolution["id"]] for resolution in catalog["resolutions"])
    frame_rates = ", ".join(str(fps) for fps in catalog["frameRates"])
    lines.extend([
        f"    public static let resolutions: [VideoResolution] = [{all_names}]",
        f"    public static let frameRates: [Int] = [{frame_rates}]",
        f"    public static let defaultResolution = {default_name}",
        f"    public static let defaultFrameRate = {catalog['defaultFps']}",
        "",
        "    public static func resolution(id: String) -> VideoResolution? {",
        "        resolutions.first { $0.id == id }",
        "    }",
        "",
        "    public static func suggestedBitrateBps(resolution: VideoResolution, fps: Int) -> Int? {",
        "        switch (resolution.id, fps) {",
    ])
    for suggestion in catalog["suggestedBitratesBps"]:
        lines.append(
            f"        case (\"{suggestion['resolutionId']}\", {suggestion['fps']}): {format_integer(suggestion['bitrateBps'])}"
        )
    lines.extend([
        "        default: nil",
        "        }",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def write_or_check(path: Path, expected: str, check: bool, label: str) -> bool:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            print(f"stale generated {label}: {path}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"generated {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated declarations are stale")
    arguments = parser.parse_args()
    catalog = load_catalog()
    android = render_android(catalog)
    swift = render_swift(catalog)
    valid = write_or_check(ANDROID_OUTPUT_PATH, android, arguments.check, "Android sender settings")
    valid = write_or_check(SWIFT_OUTPUT_PATH, swift, arguments.check, "Swift sender settings") and valid
    if arguments.check and valid:
        print("CamBridge sender settings generation: current")
    return 0 if valid else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"CamBridge sender settings generation: {error}", file=sys.stderr)
        raise SystemExit(1)
