#!/usr/bin/env python3
"""Generate the C++ CamBridge protocol constants from the JSON contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_PATH = REPOSITORY_ROOT / "protocol" / "cambridge-stream-contract.json"
SCHEMA_PATH = REPOSITORY_ROOT / "protocol" / "cambridge-stream.schema.json"
OUTPUT_PATH = (
    REPOSITORY_ROOT
    / "receiver/obs/cambridge-obs-source/src/protocol_contract.generated.hpp"
)
GENERATED_HEADER = (
    "// Generated by scripts/development/generate-cambridge-cpp-contract.py. "
    "Do not edit.\n"
)


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def scalar_constant(lines: list[str], name: str, value: Any, cpp_type: str) -> None:
    if isinstance(value, str):
        lines.append(f"inline constexpr char {name}[] = {cpp_string(value)};")
    else:
        lines.append(f"inline constexpr {cpp_type} {name} = {value};")


def render(contract: dict[str, Any], schema: dict[str, Any]) -> str:
    control = contract["control"]
    discovery = contract["discovery"]
    receiver = contract["receiver"]
    defaults = contract["defaults"]
    geometry = contract["geometry"]
    video = contract["video"]
    bitrate = contract["bitrate"]
    media = contract["media"]
    schema_properties = schema["properties"]

    lines = [
        GENERATED_HEADER.rstrip("\n"),
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace cambridge::contract {",
        "",
    ]

    scalar_constant(lines, "kContractName", contract["name"], "")
    scalar_constant(lines, "kProtocolVersion", contract["protocolVersion"], "std::uint32_t")
    lines.append("")

    scalar_constant(lines, "kControlFraming", control["framing"], "")
    scalar_constant(lines, "kMaximumControlMessageBytes", control["maxMessageBytes"], "std::size_t")
    scalar_constant(lines, "kControlConnectTimeoutMs", control["connectTimeoutMs"], "std::uint32_t")
    scalar_constant(lines, "kControlRequestTimeoutMs", control["requestTimeoutMs"], "std::uint32_t")
    lines.append("")

    scalar_constant(lines, "kDiscoveryVersion", discovery["version"], "std::uint32_t")
    scalar_constant(lines, "kDiscoveryServiceType", discovery["serviceType"], "")
    scalar_constant(lines, "kDiscoveryAddressKeyPrefix", discovery["addressKeyPrefix"], "")
    scalar_constant(lines, "kDiscoveryAddressFamily", discovery["addressFamily"], "")
    scalar_constant(lines, "kMaximumDiscoveryAddressCount", discovery["maximumAddressCount"], "std::size_t")
    txt_key_names = {
        "id": "kDiscoveryReceiverIdKey",
        "name": "kDiscoveryReceiverNameKey",
        "protocolVersion": "kDiscoveryProtocolVersionKey",
        "codec": "kDiscoveryCodecKey",
        "discoveryVersion": "kDiscoveryVersionKey",
    }
    txt_values = dict(zip(discovery["txtKeys"], discovery["txtKeys"]))
    for txt_name, constant_name in txt_key_names.items():
        scalar_constant(lines, constant_name, txt_values[txt_name], "")
    lines.append(
        "inline constexpr std::array<const char *, "
        f"{len(discovery['txtKeys'])}> kDiscoveryTxtKeys = {{"
        + ", ".join(cpp_string(value) for value in discovery["txtKeys"])
        + "};"
    )
    lines.append("")

    scalar_constant(lines, "kDefaultReceiverId", receiver["defaultId"], "")
    scalar_constant(lines, "kDefaultReceiverDisplayName", receiver["defaultDisplayName"], "")
    lines.append("")

    scalar_constant(lines, "kDefaultControlPort", defaults["controlPort"], "std::uint32_t")
    scalar_constant(lines, "kDefaultMediaRtpPort", defaults["mediaRtpPort"], "std::uint32_t")
    scalar_constant(lines, "kDefaultMediaRtcpPort", defaults["mediaRtcpPort"], "std::uint32_t")
    scalar_constant(lines, "kDefaultSenderRtcpPort", defaults["senderRtcpPort"], "std::uint32_t")
    lines.append("")

    scalar_constant(lines, "kMinimumDimension", geometry["minimumDimension"], "std::uint32_t")
    scalar_constant(lines, "kDimensionAlignment", geometry["dimensionAlignment"], "std::uint32_t")
    scalar_constant(lines, "kMaximumLongEdge", geometry["maximumLongEdge"], "std::uint32_t")
    scalar_constant(lines, "kMaximumShortEdge", geometry["maximumShortEdge"], "std::uint32_t")
    lines.append("inline constexpr std::uint32_t kDefaultMaximumLongEdge = kMaximumLongEdge;")
    lines.append("inline constexpr std::uint32_t kDefaultMaximumShortEdge = kMaximumShortEdge;")
    lines.append(
        "inline constexpr std::array<std::uint32_t, "
        f"{len(geometry['rotationDegrees'])}> kRotationDegrees = {{"
        + ", ".join(str(value) for value in geometry["rotationDegrees"])
        + "};"
    )
    lines.append("")

    scalar_constant(lines, "kMinimumFps", video["minimumFps"], "std::uint32_t")
    scalar_constant(lines, "kMaximumFps", video["maximumFps"], "std::uint32_t")
    lines.append("")

    scalar_constant(lines, "kMinimumBitrateBps", bitrate["minimumBps"], "std::uint32_t")
    scalar_constant(lines, "kMaximumBitrateBps", bitrate["maximumBps"], "std::uint32_t")
    lines.append("")

    scalar_constant(lines, "kMediaTransport", media["transport"], "")
    scalar_constant(lines, "kRtpPayloadType", media["payloadType"], "std::uint32_t")
    scalar_constant(lines, "kRtxPayloadType", media["rtxPayloadType"], "std::uint32_t")
    scalar_constant(lines, "kRtpClockRateHz", media["clockRateHz"], "std::uint32_t")
    scalar_constant(lines, "kRtpMtuBytes", media["mtuBytes"], "std::size_t")
    scalar_constant(lines, "kTwccExtensionId", media["twccExtensionId"], "std::uint32_t")
    scalar_constant(lines, "kRtpSessionIndex", media["rtpSessionIndex"], "std::uint32_t")
    scalar_constant(lines, "kMaximumAccessUnitBytes", media["maxAccessUnitBytes"], "std::size_t")
    scalar_constant(lines, "kMailboxCapacity", media["mailboxCapacity"], "std::size_t")
    scalar_constant(lines, "kTexturePoolSlots", media["texturePoolSlots"], "std::size_t")
    scalar_constant(lines, "kKeyframeIntervalSeconds", media["keyframeIntervalSeconds"], "std::uint32_t")
    lines.append("")

    scalar_constant(lines, "kCodecH264", schema_properties["codec"]["const"], "")
    lines.append("")

    for message_name, message_shape in contract["messages"].items():
        scalar_constant(lines, f"kMessageShape{message_name.capitalize()}", message_shape, "")
    lines.append("")
    for message_name in contract["messages"]:
        scalar_constant(lines, f"kMessage{message_name.capitalize()}", message_name, "")
    lines.append("")

    # These values are schema rules rather than transport values, but keeping
    # them generated prevents C++ validation from drifting from the JSON shape.
    scalar_constant(lines, "kMinimumGeneration", schema_properties["generation"]["minimum"], "std::uint32_t")
    scalar_constant(lines, "kMaximumSessionIdBytes", schema_properties["sessionId"]["maxLength"], "std::size_t")
    scalar_constant(lines, "kMaximumErrorBytes", schema_properties["error"]["maxLength"], "std::size_t")
    scalar_constant(lines, "kMinimumPort", schema_properties["mediaRtpPort"]["minimum"], "std::uint32_t")
    scalar_constant(lines, "kMaximumPort", schema_properties["mediaRtpPort"]["maximum"], "std::uint32_t")
    lines.append("inline constexpr std::size_t kControlHeaderBytes = sizeof(std::uint32_t);")
    lines.extend(["", "} // namespace cambridge::contract", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the committed output is stale")
    arguments = parser.parse_args()
    contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    generated = render(contract, schema)
    if arguments.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != generated:
            print(f"stale generated C++ contract: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print("CamBridge C++ contract generation: current")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f"CamBridge C++ contract generation: {error}", file=sys.stderr)
        raise SystemExit(1)
