#!/usr/bin/env python3
"""Generate the committed iOS version xcconfig from the component manifest."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPOSITORY_ROOT / "sender/ios/Configuration/GeneratedVersion.xcconfig"
SEMVER_PATTERN = re.compile(r"^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)$")
GENERATED_HEADER = "// Generated by scripts/development/generate-ios-version.py. Do not edit.\n"
SCRIPT_DIRECTORY = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIRECTORY))

from cambridge_component_versions import (  # noqa: E402
    DEFERRED_IOS_BUILD_VERSION,
    DEFERRED_IOS_MARKETING_VERSION,
    component_version,
)


def expected_output() -> str:
    version = component_version("ios")
    if version is None:
        return (
            GENERATED_HEADER
            + "// iOS sender release version is deferred.\n"
            + f"CAMBRIDGE_MARKETING_VERSION = {DEFERRED_IOS_MARKETING_VERSION}\n"
            + f"CAMBRIDGE_BUILD_VERSION = {DEFERRED_IOS_BUILD_VERSION}\n"
        )
    match = SEMVER_PATTERN.fullmatch(version)
    if match is None:
        raise ValueError("VERSION must contain major.minor.patch numeric components")
    major = int(match.group("major"))
    minor = int(match.group("minor"))
    patch = int(match.group("patch"))
    return (
        GENERATED_HEADER
        + f"CAMBRIDGE_MARKETING_VERSION = {major}.{minor}.{patch}\n"
        + f"CAMBRIDGE_BUILD_VERSION = {major}.{minor}.{patch}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the committed output is stale")
    arguments = parser.parse_args()
    output = expected_output()
    if arguments.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != output:
            print(f"stale generated iOS version: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print("iOS version generation: current")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"iOS version generation: {error}", file=sys.stderr)
        raise SystemExit(1)
