#!/usr/bin/env python3
"""Generate the Swift CamBridge contract constants from the v6 JSON contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_PATH = REPOSITORY_ROOT / "protocol/cambridge-stream-contract.json"
SCHEMA_PATH = REPOSITORY_ROOT / "protocol/cambridge-stream.schema.json"
OUTPUT_PATH = (
    REPOSITORY_ROOT
    / "sender/ios/Packages/CamBridgeCore/Sources/CamBridgeCore/Contract/CamBridgeContract.generated.swift"
)
GENERATED_HEADER = "// Generated by scripts/development/generate-cambridge-swift-contract.py. Do not edit.\n"


class DeferredSwiftContract(ValueError):
    """The iOS sender is deferred while the shared contract is on v7."""

EXPECTED_TOP_LEVEL = {"name", "protocolVersion", "control", "discovery", "receiver", "defaults", "geometry", "video", "bitrate", "media", "messages"}
EXPECTED_FIELDS = {
    "control": {"framing", "maxMessageBytes", "connectTimeoutMs", "requestTimeoutMs"},
    "discovery": {"version", "serviceType", "txtKeys", "addressKeyPrefix", "addressFamily", "maximumAddressCount"},
    "receiver": {"defaultId", "defaultDisplayName"},
    "defaults": {"controlPort", "mediaPortOffset"},
    "geometry": {"minimumDimension", "dimensionAlignment", "maximumLongEdge", "maximumShortEdge", "rotationDegrees"},
    "video": {"minimumFps", "maximumFps"},
    "bitrate": {"minimumBps", "maximumBps"},
    "media": {
        "transport", "payloadType", "clockRateHz", "rtpHeaderBytes", "mtuBytes", "maxDatagramBytes",
        "maxAccessUnitBytes", "maxReorderPackets", "mailboxCapacity", "texturePoolSlots",
        "reorderDeadlineMs", "keyframeIntervalSeconds",
    },
    "messages": {"probe", "capabilities", "hello", "accepted", "stop", "error"},
}
MESSAGE_NAMES = ("probe", "capabilities", "hello", "accepted", "stop", "error")


def load_contract() -> tuple[dict[str, Any], dict[str, Any]]:
    value = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    if value.get("protocolVersion") != 6:
        raise DeferredSwiftContract(
            "the iOS sender contract generator is deferred until the iOS transport is migrated"
        )
    if not isinstance(value, dict) or set(value) != EXPECTED_TOP_LEVEL:
        raise ValueError("the CamBridge contract has an unsupported top-level shape")
    for section, expected in EXPECTED_FIELDS.items():
        section_value = value[section]
        if not isinstance(section_value, dict) or set(section_value) != expected:
            raise ValueError(f"the CamBridge contract section {section!r} has an unsupported shape")
    if value["protocolVersion"] != 6:
        raise ValueError("the Swift generator only supports the CamBridge v6 contract")
    if value["discovery"]["addressFamily"] != "ipv4":
        raise ValueError("the Swift generator only supports the declared IPv4 discovery family")
    if value["geometry"]["rotationDegrees"] != [0, 90, 180, 270]:
        raise ValueError("the Swift generator requires all four right-angle rotations")
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    schema_properties = schema.get("properties")
    if not isinstance(schema_properties, dict):
        raise ValueError("the CamBridge schema has no supported properties object")
    for property_name in ("requestId", "receiverId", "displayName", "sessionId", "profileId", "error", "mediaPort", "generation"):
        if property_name not in schema_properties:
            raise ValueError(f"the CamBridge schema is missing {property_name}")
    codec_value = schema_properties.get("codec", {}).get("const")
    if not isinstance(codec_value, str) or not codec_value:
        raise ValueError("the CamBridge schema must declare a codec constant")
    return value, schema


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def swift_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return swift_string(value)
    if isinstance(value, list) and all(isinstance(item, (str, int)) for item in value):
        values = ", ".join(swift_scalar(item) for item in value)
        return f"[{values}]"
    raise ValueError(f"unsupported contract scalar {value!r}")


def constant_name(key: str) -> str:
    names = {
        "maxMessageBytes": "maximumMessageBytes",
        "connectTimeoutMs": "connectTimeoutMilliseconds",
        "requestTimeoutMs": "requestTimeoutMilliseconds",
        "maximumAddressCount": "maximumAddressCount",
    }
    return names.get(key, key)


def render(contract: dict[str, Any], schema: dict[str, Any]) -> str:
    lines = [GENERATED_HEADER.rstrip("\n"), "import Foundation", "", "public enum CamBridgeContract {"]
    lines.append(f"    public static let name = {swift_string(contract['name'])}")
    lines.append(f"    public static let protocolVersion = {contract['protocolVersion']}")
    sections = (
        ("Control", "control"),
        ("Discovery", "discovery"),
        ("Receiver", "receiver"),
        ("Defaults", "defaults"),
        ("Geometry", "geometry"),
        ("Video", "video"),
        ("Bitrate", "bitrate"),
        ("Media", "media"),
    )
    for type_name, section_name in sections:
        lines.extend(["", f"    public enum {type_name} {{"])
        for key, value in contract[section_name].items():
            lines.append(f"        public static let {constant_name(key)} = {swift_scalar(value)}")
        lines.append("    }")
    schema_properties = schema["properties"]
    lines.extend([
        "",
        "    public enum Codec {",
        f"        public static let h264 = {swift_string(schema_properties['codec']['const'])}",
        "    }",
        "",
        "    public enum Validation {",
        f"        public static let maximumIdentifierLength = {schema_properties['requestId']['maxLength']}",
        f"        public static let maximumProfileIdentifierLength = {schema_properties['profileId']['maxLength']}",
        f"        public static let maximumErrorLength = {schema_properties['error']['maxLength']}",
        f"        public static let minimumPort = {schema_properties['mediaPort']['minimum']}",
        f"        public static let maximumPort = {schema_properties['mediaPort']['maximum']}",
        f"        public static let minimumGeneration = {schema_properties['generation']['minimum']}",
        "    }",
    ])
    lines.extend(["", "    public enum MessageType {"])
    for message_name in MESSAGE_NAMES:
        lines.append(f"        public static let {message_name} = {swift_string(message_name)}")
    lines.extend(["    }", "", "    public enum MessageShape {"])
    for message_name in MESSAGE_NAMES:
        lines.append(f"        public static let {message_name} = {swift_string(contract['messages'][message_name])}")
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the committed output is stale")
    arguments = parser.parse_args()
    try:
        contract, schema = load_contract()
    except DeferredSwiftContract as error:
        if arguments.check:
            print(f"CamBridge Swift contract generation: deferred ({error})")
            return 0
        raise
    generated = render(contract, schema)
    if arguments.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != generated:
            print(f"stale generated Swift contract: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print("CamBridge Swift contract generation: current")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"CamBridge Swift contract generation: {error}", file=sys.stderr)
        raise SystemExit(1)
