// Generated by scripts/development/generate-cambridge-sender-modes.py. Do not edit.
package dev.cambridge.sender.session

import dev.cambridge.sender.model.VideoProfile

object VideoProfiles {
    const val MEGABIT = 1_000_000
    const val PROFILE_ID = "sender"

    val PROFILE_1080P30: VideoProfile = VideoProfile(
        id = "1080p30",
        width = 1920,
        height = 1080,
        fps = 30,
        minimumBitrateBps = 1_000_000,
        defaultBitrateBps = 5_000_000,
        maximumBitrateBps = 100_000_000,
        bitrateStepBps = 1_000_000,
        keyframeIntervalSeconds = 1,
    )

    val PROFILE_1080P60: VideoProfile = VideoProfile(
        id = "1080p60",
        width = 1920,
        height = 1080,
        fps = 60,
        minimumBitrateBps = 1_000_000,
        defaultBitrateBps = 10_000_000,
        maximumBitrateBps = 100_000_000,
        bitrateStepBps = 1_000_000,
        keyframeIntervalSeconds = 1,
    )

    val PROFILE_2K30: VideoProfile = VideoProfile(
        id = "2k30",
        width = 2560,
        height = 1440,
        fps = 30,
        minimumBitrateBps = 1_000_000,
        defaultBitrateBps = 9_000_000,
        maximumBitrateBps = 100_000_000,
        bitrateStepBps = 1_000_000,
        keyframeIntervalSeconds = 1,
    )

    val PROFILE_2K60: VideoProfile = VideoProfile(
        id = "2k60",
        width = 2560,
        height = 1440,
        fps = 60,
        minimumBitrateBps = 1_000_000,
        defaultBitrateBps = 18_000_000,
        maximumBitrateBps = 100_000_000,
        bitrateStepBps = 1_000_000,
        keyframeIntervalSeconds = 1,
    )

    val normal: List<VideoProfile> = listOf(PROFILE_1080P30, PROFILE_1080P60, PROFILE_2K30, PROFILE_2K60)
    val all: List<VideoProfile> = normal
    val qualityProfiles: List<VideoProfile> = normal.distinctBy { profile -> profile.width to profile.height }
    val default: VideoProfile = PROFILE_1080P30

    fun modeFor(width: Int, height: Int, fps: Int): VideoProfile? = all.firstOrNull { profile ->
        profile.width == width && profile.height == height && profile.fps == fps
    }

    fun modeId(width: Int, height: Int, fps: Int): String? = modeFor(width, height, fps)?.id

    fun profilesForResolution(profile: VideoProfile): List<VideoProfile> = all.filter { candidate ->
        candidate.width == profile.width && candidate.height == profile.height
    }

    fun profileForResolution(width: Int, height: Int, fps: Int): VideoProfile? = modeFor(width, height, fps)
}
