// Generated by scripts/development/generate-cambridge-cpp-contract.py. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace cambridge::contract {

inline constexpr char kContractName[] = "cambridge-stream";
inline constexpr std::uint32_t kProtocolVersion = 6;

inline constexpr char kControlFraming[] = "uint32-be-length-prefixed-json";
inline constexpr std::size_t kMaximumControlMessageBytes = 8192;
inline constexpr std::uint32_t kControlConnectTimeoutMs = 2000;
inline constexpr std::uint32_t kControlRequestTimeoutMs = 2000;

inline constexpr std::uint32_t kDiscoveryVersion = 1;
inline constexpr char kDiscoveryServiceType[] = "_cambridge._tcp";
inline constexpr char kDiscoveryAddressKeyPrefix[] = "address";
inline constexpr char kDiscoveryAddressFamily[] = "ipv4";
inline constexpr std::size_t kMaximumDiscoveryAddressCount = 16;
inline constexpr char kDiscoveryReceiverIdKey[] = "id";
inline constexpr char kDiscoveryReceiverNameKey[] = "name";
inline constexpr char kDiscoveryProtocolVersionKey[] = "protocolVersion";
inline constexpr char kDiscoveryCodecKey[] = "codec";
inline constexpr char kDiscoveryVersionKey[] = "discoveryVersion";
inline constexpr std::array<const char *, 6> kDiscoveryTxtKeys = {"id", "name", "protocolVersion", "codec", "discoveryVersion", "address<N>"};

inline constexpr char kDefaultReceiverId[] = "cambridge-obs-source";
inline constexpr char kDefaultReceiverDisplayName[] = "OBS receiver";

inline constexpr std::uint32_t kDefaultControlPort = 55031;
inline constexpr std::uint32_t kDefaultMediaPortOffset = 1;
inline constexpr std::uint32_t kDefaultMediaPort = kDefaultControlPort + kDefaultMediaPortOffset;

inline constexpr std::uint32_t kMinimumDimension = 16;
inline constexpr std::uint32_t kDimensionAlignment = 2;
inline constexpr std::uint32_t kMaximumLongEdge = 3840;
inline constexpr std::uint32_t kMaximumShortEdge = 2160;
inline constexpr std::uint32_t kDefaultMaximumLongEdge = kMaximumLongEdge;
inline constexpr std::uint32_t kDefaultMaximumShortEdge = kMaximumShortEdge;
inline constexpr std::array<std::uint32_t, 4> kRotationDegrees = {0, 90, 180, 270};

inline constexpr std::uint32_t kMinimumFps = 1;
inline constexpr std::uint32_t kMaximumFps = 120;

inline constexpr std::uint32_t kMinimumBitrateBps = 100000;
inline constexpr std::uint32_t kMaximumBitrateBps = 100000000;

inline constexpr char kMediaTransport[] = "rtp-h264-udp-unicast";
inline constexpr std::uint32_t kRtpPayloadType = 96;
inline constexpr std::uint32_t kRtpClockRateHz = 90000;
inline constexpr std::size_t kRtpHeaderBytes = 12;
inline constexpr std::size_t kRtpMtuBytes = 1200;
inline constexpr std::size_t kMaximumRtpDatagramBytes = 1500;
inline constexpr std::size_t kMaximumAccessUnitBytes = 8388608;
inline constexpr std::size_t kMaximumInFlightAccessUnits = 2;
inline constexpr std::size_t kMaximumReorderPackets = 64;
inline constexpr std::size_t kMailboxCapacity = 1;
inline constexpr std::size_t kTexturePoolSlots = 3;
inline constexpr std::uint32_t kDefaultMaximumDecoderQueueAgeMs = 100;
inline constexpr std::uint32_t kDefaultMaximumLiveFrameAgeMs = 250;
inline constexpr std::uint32_t kDefaultReorderDeadlineMs = 20;
inline constexpr std::uint32_t kKeyframeIntervalSeconds = 1;

inline constexpr char kCodecH264[] = "h264";

inline constexpr char kMessageShapeProbe[] = "{protocolVersion:6, type:probe, requestId}";
inline constexpr char kMessageShapeCapabilities[] = "{protocolVersion:6, type:capabilities, requestId, receiverId, displayName, maxLongEdge, maxShortEdge}";
inline constexpr char kMessageShapeHello[] = "{protocolVersion:6, type:hello, sessionId, generation, profileId, codec, codedWidth, codedHeight, rotationDegrees, fps, bitrateBps}";
inline constexpr char kMessageShapeAccepted[] = "{protocolVersion:6, type:accepted, sessionId, generation, profileId, mediaPort, maxLongEdge, maxShortEdge}";
inline constexpr char kMessageShapeStop[] = "{protocolVersion:6, type:stop, sessionId, generation}";
inline constexpr char kMessageShapeError[] = "{protocolVersion:6, type:error, error}";

inline constexpr char kMessageProbe[] = "probe";
inline constexpr char kMessageCapabilities[] = "capabilities";
inline constexpr char kMessageHello[] = "hello";
inline constexpr char kMessageAccepted[] = "accepted";
inline constexpr char kMessageStop[] = "stop";
inline constexpr char kMessageError[] = "error";

inline constexpr std::uint32_t kMinimumGeneration = 1;
inline constexpr std::size_t kMaximumSessionIdBytes = 128;
inline constexpr std::size_t kMaximumErrorBytes = 512;
inline constexpr std::uint32_t kMinimumPort = 1;
inline constexpr std::uint32_t kMaximumPort = 65535;
inline constexpr std::size_t kControlHeaderBytes = sizeof(std::uint32_t);

} // namespace cambridge::contract
